version: '3.7'

services:
    basedatoslocal:
        image: mysql/mysql-server:5.6.25
        container_name: basedatoslocal
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=javawebapp
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ~/compose-mysql-server-5/mysql-data:/var/lib/mysql

    phpmyadmin:
        depends_on:
            - basedatoslocal
        image: phpmyadmin/phpmyadmin
        container_name: devpmalocal
        environment:
            - PMA_HOST=basedatoslocal
#            PMA_PORT: 3307
#            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8082:80
